In [ ]:
import numpy as np
import random as r

In [ ]:
def matrix_by_random(size:int):
  matrix = np.array([])
  for i in range(0, size):
    for j in range(0, size):
      matrix = np.append(matrix, r.randint(-5, 15))
  matrix = matrix.reshape(size, size)
  return matrix

In [ ]:
def matrix_by_file():
  matrix = np.array([])
  from google.colab import drive
  drive.mount('/content/drive')
  filepath = "/content/drive/MyDrive/Colab Notebooks/BigData_L-6.txt"
  file = open(filepath, "r")
  data = file.read()
  data = data.replace("\n", " ")
  data = data.split(" ")
  for i in range(len(data)):
    matrix = np.append(matrix, int(data[i]))
  matrix = matrix.reshape(int(np.sqrt(len(data))), int(np.sqrt(len(data))))
  return matrix

In [ ]:
def normal_matrix(matrix:int):
  normal = 0.0
  max = 0.0
  for i in range(0, len(matrix)):
    max = 0
    for j in range(0, len(matrix)):
      max += np.absolute(matrix[i][j])
    if (max > normal):
      normal = max
  return normal

In [ ]:
def qualifier(matrix:int):
  a = 0.0
  b = 0.0
  c = 0
  if (len(matrix) > 2):
    for i in range(0, len(matrix)):
      b = 1.0
      for j in range(0, len(matrix)):
        c = j + i
        if (c >= len(matrix)):
          c -= len(matrix)
        b = b * matrix[j][c]
      a += b
    for i in range(len(matrix) - 1, -1, -1):
      b = 1.0
      for j in range(0, len(matrix)):
        c = i - j
        if (c < 0):
          c += len(matrix)
        b = b * matrix[j][c]
      a -= b
  else:
    a = (matrix[0][0] * matrix[1][1]) - (matrix[0][1] * matrix[1][0])
  return a

In [ ]:
def inverted(matrix:int):
  buffer = 0.0
  qual = qualifier(matrix)

  if (qual != 0):
    transpose = matrix
    for i in range(0, len(matrix)):
      for j in range(i + 1, len(matrix)):
        buffer = transpose[j][i]
        transpose[j][i] = transpose[i][j]
        transpose[i][j] = buffer

    minor = np.zeros((len(matrix), len(matrix)))
    auxilary = np.zeros((len(matrix) - 1, len(matrix) - 1))
    for i in range(0, len(matrix)):
      for j in range(0, len(matrix)):
        for k in range (0 , len(matrix)):
          for l in range (0, len(matrix)):
            if (k != i and l != j):
              if (k > i):
                if (l > j):
                  auxilary[k - 1][l - 1] = transpose[l][k]
                else:
                  auxilary[k - 1][l] = transpose[l][k]     
              else:
                if (l > j):
                  auxilary[k][l - 1] = transpose[l][k]
                else:
                  auxilary[k][l] = transpose[l][k]
        if (len(auxilary) >= 2):
          minor[i][j] = qualifier(auxilary)
        else:
          minor[i][j] = auxilary[0][0]
    reversed = np.zeros((len(matrix), len(matrix)))
    for i in range(0, len(matrix)):
      for j in range(0, len(matrix)):
        reversed[j][i] = (minor[j][i] * (1 / qualifier(matrix)))
  else:
    print("Определитель матрицы равняется нулю!")
  return reversed

In [ ]:
matrix = np.array([])
print("Введите размерность матрицы(N * N).")
print("Внимание! При вводе значения 0 матрица будет взята из файла!")
matrix_size = int(input("Размерность матрицы: "))
print("")
if (matrix_size == 0):
 matrix = matrix_by_file()
else:
  matrix = matrix_by_random(matrix_size)

if (matrix_size <= 15):
  print(matrix)
  
print("Число обусловленности матрицы: ", round(normal_matrix(matrix) * normal_matrix(inverted(matrix)), 3))

Введите размерность матрицы(N * N).
Внимание! При вводе значения 0 матрица будет взята из файла!
Размерность матрицы: 5

[[-5. 14. 11.  3. 11.]
 [ 8. 12.  3. -4.  7.]
 [-2.  4. 12.  7. -2.]
 [14.  7. 14. 10. 13.]
 [ 9.  2. 13. -5. -4.]]
Число обусловленности матрицы:  37.913
