In [ ]:
import numpy as np

In [ ]:
class Vector:
    def __init__(self, x, y, z, func):
        self.x = x
        self.y = y
        self.z = z
        self.func = func

In [ ]:
function = 1 ** 2 + 0 ** 2 + 1 ** 2 + 1 - 2 * 0
vector = Vector(1, 0, 1, function)
v = np.array([[vector.x, vector.y, vector.z, vector.func]])
function = 2 ** 2 + 0 ** 2 + 1 ** 2 + 2 - 2 * 0
vector = Vector(2, 0, 1, function)
v = np.append(v, [[vector.x, vector.y, vector.z, vector.func]], axis = 0)
function = 1 ** 2 + 1 ** 2 + 1 ** 2 + 1 - 2 * 1
vector = Vector(1, 1, 1, function)
v = np.append(v, [[vector.x, vector.y, vector.z, vector.func]], axis = 0)
function = 1 ** 2 + 0 ** 2 + 2 ** 2 + 1 - 2 * 0
vector = Vector(1, 0, 2, function)
v = np.append(v, [[vector.x, vector.y, vector.z, vector.func]], axis = 0)
print(v)

[[1 0 1 3]
 [2 0 1 7]
 [1 1 1 2]
 [1 0 2 6]]


In [ ]:
def byDF_key(vector:float):
    return np.absolute(vector[3])

In [ ]:
for i in range(0, 10):
    v = sorted(v, key = byDF_key)

    middle_x_1 = (v[0][0] + v[1][0] + v[2][0]) / 3
    middle_x_2 = (v[0][1] + v[1][1] + v[2][1]) / 3
    middle_x_3 = (v[0][2] + v[1][2] + v[2][2]) / 3

    middle_arr = np.array([middle_x_1, middle_x_2, middle_x_3])
    #Reflection

    new_x_1 = middle_x_1 + (middle_x_1 - v[3][0])
    new_x_2 = middle_x_2 + (middle_x_2 - v[3][1])
    new_x_3 = middle_x_3 + (middle_x_3 - v[3][2])
    function = new_x_1 ** 2 + new_x_2 ** 2 + new_x_3 ** 2 + new_x_1 - 2 * new_x_2

    if (np.absolute(function) < v[2][3]):

      v[3][0] = new_x_1
      v[3][1] = new_x_2
      v[3][2] = new_x_3
      v[3][3] = function

    else:
      if (np.absolute(function) < v[3][3]):

        v[3][0] = new_x_1
        v[3][1] = new_x_2
        v[3][2] = new_x_3
        v[3][3] = function

      new_x_1 = (v[3][0] - middle_x_1) / 2
      new_x_2 = (v[3][1] - middle_x_2) / 2
      new_x_3 = (v[3][2] - middle_x_3) / 2
      function = new_x_1 ** 2 + new_x_2 ** 2 + new_x_3 ** 2 + new_x_1 - 2 * new_x_2

      if (np.absolute(function) < v[3][3]):

        v[3][0] = new_x_1
        v[3][1] = new_x_2
        v[3][2] = new_x_3
        v[3][3] = function       

    #Expansion
    new_x_1 = middle_x_1 + 2 * (v[3][0] - middle_x_1)
    new_x_2 = middle_x_2 + 2 * (v[3][1] - middle_x_2)
    new_x_3 = middle_x_3 + 2 * (v[3][2] - middle_x_3)
    function = new_x_1 ** 2 + new_x_2 ** 2 + new_x_3 ** 2 + new_x_1 - 2 * new_x_2

    if (np.absolute(function) < v[0][3]):
      v[3][0] = new_x_1
      v[3][1] = new_x_2
      v[3][2] = new_x_3
      v[3][3] = function

    #Contraction
    new_x_1 = middle_x_1 + 0.5 * (v[3][0] - middle_x_1)
    new_x_2 = middle_x_2 + 0.5 * (v[3][1] - middle_x_2)
    new_x_3 = middle_x_3 + 0.5 * (v[3][2] - middle_x_3)
    function = new_x_1 ** 2 + new_x_2 ** 2 + new_x_3 ** 2 + new_x_1 - 2 * new_x_2

    if (np.absolute(function) < v[3][3]):
      v[3][0] = new_x_1
      v[3][1] = new_x_2
      v[3][2] = new_x_3
      v[3][3] = function

v = sorted(v, key = byDF_key)
print("Лучшая точка: ", v[0])

Лучшая точка:  [0 0 0 0]
