In [0]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np

In [0]:
model = Sequential()
model.add(Dense(4, input_dim=2, activation='softmax'))
model.add(Dense(1, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

NameError: ignored

In [0]:
X = np.array([[0, 0], [0, 1], [0, 2], [0, 3], [1, 0], [1, 1], [1, 2], [1, 3], [2, 0], [2, 1], [2, 2], [2, 3], [3, 0], [3, 1], [3, 2], [3, 3]])
Y = np.array([1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [0]:
model.fit(X, Y, epochs=1000)

In [0]:
model.predict(X)

array([[0.7019185 ],
       [0.87498355],
       [0.9097309 ],
       [0.9185749 ],
       [0.24789625],
       [0.6945226 ],
       [0.87173104],
       [0.90863025],
       [0.07108971],
       [0.24057814],
       [0.6846116 ],
       [0.86757624],
       [0.04198545],
       [0.06905666],
       [0.23470324],
       [0.6721437 ]], dtype=float32)

In [0]:
model.get_weights()

[array([[ 0.2614039 ,  1.427628  , -1.297871  ,  1.6539055 ],
        [-0.24954993, -1.3105624 ,  1.1701292 , -1.8484619 ]],
       dtype=float32),
 array([-0.40290347, -1.0321546 ,  0.934943  , -0.9522694 ], dtype=float32),
 array([[-0.27211168],
        [-1.9466728 ],
        [ 2.0194454 ],
        [-1.7308383 ]], dtype=float32),
 array([0.508586], dtype=float32)]