#**Спам-фильтр на основе Байесовского классификатора**

Данные принимать из текстового [файла](https://drive.google.com/file/d/1fBtviA295B6RArZ2Lt68sRh0eziWXMlJ/view?usp=sharing). Файл содержит спамные и хамные смс-сообщения, размеченные spam/ham (обратите внимание - метка класса стоит перед сообщением и отделена от него табуляцией '\t')

Выполните предобработку текста: 
- приведение к нижнему регистру; 
- удаление знаков пунткуации; 
- замена чисел одним каким-либо значением (например, 2015 - **2**, 33 - **2**, 04 - **2**, т.к. числовые значения не несут никакой нагрузки на определение класса. с таким же успехом числа можно удалить )





In [0]:
import numpy as np
import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import GaussianNB

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
def text_editor(text):
  text = re.sub(r'\d+', '', text)
  text = re.sub(r'[^\w\s]','', text)
  text = text.lower() 
  return text

In [0]:
spam_ham_file = open('/content/drive/My Drive/SMSSpamCollection.txt', 'r')
spam_ham_categories = []
line_arr = []
for line in spam_ham_file:
  line_text = line.strip().split('\t')
  if line_text[0] == 'ham':
    spam_ham_categories.append(0)
  else:
    spam_ham_categories.append(1)
  line_arr.append(text_editor(line_text[1]))

In [0]:
for i in range(10):
  print(line_arr[i])

go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat
ok lar joking wif u oni
free entry in  a wkly comp to win fa cup final tkts st may  text fa to  to receive entry questionstd txt ratetcs apply overs
u dun say so early hor u c already then say
nah i dont think he goes to usf he lives around here though
freemsg hey there darling its been  weeks now and no word back id like some fun you up for it still tb ok xxx std chgs to send  to rcv
even my brother is not like to speak with me they treat me like aids patent
as per your request melle melle oru minnaminunginte nurungu vettam has been set as your callertune for all callers press  to copy your friends callertune
winner as a valued network customer you have been selected to receivea  prize reward to claim call  claim code kl valid  hours only
had your mobile  months or more u r entitled to update to the latest colour mobiles with camera for free call the mobile update co free on 


Создайте мешок слов

In [0]:
#Ваш код
tokenization = CountVectorizer()
tokenization.fit(line_arr)

bag_of_words = tokenization.transform(line_arr).toarray()
frequency_matrix = pd.DataFrame(bag_of_words, columns = tokenization.get_feature_names())

Реализуйте наивный Байесовский классификатор

In [0]:
#Ваш код
tokenization = CountVectorizer()
data = tokenization.fit_transform(line_arr)

model = GaussianNB()
model.fit(data.toarray(), spam_ham_categories)

GaussianNB(priors=None, var_smoothing=1e-09)


Определите принадлежность к классу произвольного смс-сообщения, которое не участвовало в обучении


In [0]:
#Ваш код
is_it_ham = tokenization.transform([text_editor("I think electric cars are a great invention. It would be nice to buy one.")])
is_it_spam = tokenization.transform([text_editor("You have still not claimed the compensation you are due for the accident you had. To start the process please reply YES. To opt out text STOP")])

print(model.predict_proba(is_it_ham.toarray()))
print(model.predict_proba(is_it_spam.toarray()))

print(model.predict(is_it_ham.toarray()))
print(model.predict(is_it_spam.toarray()))

[[1. 0.]]
[[0. 1.]]
[0]
[1]


#Пример из лекции

[файл](https://drive.google.com/open?id=1ietVcltMgGgOl_QHITWYlk4KsozAsz4g) с байесовской арифметикой в эксельке (мешок слов заполните сами, а также ячейки I2:I4 и J2:J4)


In [0]:
import numpy as np
sentens = ['предоставляю','услуги','бухгалтера','спешите','купить','велосипед','надо','купить','молоко']
answer = ['spam','spam','ham']

from sklearn import preprocessing

le = preprocessing.LabelEncoder()
x=np.array(le.fit_transform(sentens)).reshape((3,3))
label=np.array(le.fit_transform(answer)).reshape((3,))

print (x)
print (label)



[[5 7 0]
 [6 2 1]
 [4 2 3]]
[1 1 0]


In [0]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(x,label)

predicted= model.predict([[4,2,9]]) #надо(4), купить(2), диван(9 - отсутствует в коллекции слов)
print ("Predicted Value:", predicted)

Predicted Value: [1]
